"""phase2 income_band + assessment state

Revision ID: 4896b7a906d0
Revises: 4ed2dd43649f
Create Date: 2026-10-02 23:26:42.083073
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4896b7a906d0'
down_revision: Union[str, None] = '4ed2dd43649f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'status',
                sa.String(length=20),
                server_default='in_progress',
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column('state_json', sa.JSON(), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('income_band', sa.String(length=10), nullable=True))
        # SQLite cannot introspect CHECK constraints, so autogenerate omits this one.
        batch_op.create_check_constraint(
            'ck_student_income',
            "income_band IN ('lt_1l', '1l_3l', '3l_6l', 'gt_6l')",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('ck_student_income', type_='check')
        batch_op.drop_column('income_band')

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_column('state_json')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
