"""initial schema

Revision ID: 4ed2dd43649f
Revises: 
Create Date: 2026-10-02 22:10:17.959591
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '4ed2dd43649f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('occupations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('name_hi', sa.String(length=200), nullable=True),
    sa.Column('nco_code', sa.String(length=32), nullable=True),
    sa.Column('onet_code', sa.String(length=32), nullable=True),
    sa.Column('esco_uri', sa.String(length=255), nullable=True),
    sa.Column('nsqf_level', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('riasec_r', sa.Float(), nullable=False),
    sa.Column('riasec_i', sa.Float(), nullable=False),
    sa.Column('riasec_a', sa.Float(), nullable=False),
    sa.Column('riasec_s', sa.Float(), nullable=False),
    sa.Column('riasec_e', sa.Float(), nullable=False),
    sa.Column('riasec_c', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('source_year', sa.Integer(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('occupations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_occupations_name_en'), ['name_en'], unique=True)
        batch_op.create_index(batch_op.f('ix_occupations_nco_code'), ['nco_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_occupations_nsqf_level'), ['nsqf_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_occupations_onet_code'), ['onet_code'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('student', 'parent', 'counsellor', 'admin')", name='ck_user_role'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occupation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('nsqf_level', sa.Integer(), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('min_edu', sa.String(length=20), nullable=True),
    sa.Column('fee_inr', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cert_body', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('source_year', sa.Integer(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['occupation_id'], ['occupations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_nsqf_level'), ['nsqf_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_occupation_id'), ['occupation_id'], unique=False)

    op.create_table('market',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occupation_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('avg_salary_inr', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('demand_index', sa.Float(), nullable=True),
    sa.Column('placement_rate', sa.Float(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('source_year', sa.Integer(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['occupation_id'], ['occupations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_occupation_id'), ['occupation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_state'), ['state'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('edu_level', sa.String(length=20), nullable=False),
    sa.Column('district', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('budget_band', sa.String(length=10), nullable=False),
    sa.Column('relocate_ok', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('max_duration_months', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("budget_band IN ('low', 'mid', 'high')", name='ck_student_budget'),
    sa.CheckConstraint("edu_level IN ('8th', '10th', '12th', 'ITI', 'diploma', 'graduate')", name='ck_student_edu'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_user_id'), ['user_id'], unique=True)

    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('items_answered', sa.Integer(), nullable=False),
    sa.Column('riasec_r', sa.Float(), nullable=False),
    sa.Column('riasec_i', sa.Float(), nullable=False),
    sa.Column('riasec_a', sa.Float(), nullable=False),
    sa.Column('riasec_s', sa.Float(), nullable=False),
    sa.Column('riasec_e', sa.Float(), nullable=False),
    sa.Column('riasec_c', sa.Float(), nullable=False),
    sa.Column('apt_num', sa.Float(), nullable=False),
    sa.Column('apt_verbal', sa.Float(), nullable=False),
    sa.Column('apt_spatial', sa.Float(), nullable=False),
    sa.Column('apt_mech', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessments_student_id'), ['student_id'], unique=False)

    op.create_table('centres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('district', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('source_year', sa.Integer(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('centres', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_centres_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_centres_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_centres_state'), ['state'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('occupation_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reasons_json', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['occupation_id'], ['occupations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_occupation_id'), ['occupation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_student_id'), ['student_id'], unique=False)

    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('created_at_dt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rooms_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_rooms_student_id'), ['student_id'], unique=False)

    op.create_table('criteria_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('salary', sa.Float(), nullable=False),
    sa.Column('local_jobs', sa.Float(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'user_id', name='uq_criteria_weights')
    )
    with op.batch_alter_table('criteria_weights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_criteria_weights_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_criteria_weights_user_id'), ['user_id'], unique=False)

    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('helpful', sa.Boolean(), nullable=False),
    sa.Column('chosen', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_recommendation_id'), ['recommendation_id'], unique=False)

    op.create_table('room_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'user_id', name='uq_room_member')
    )
    with op.batch_alter_table('room_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_members_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_members_user_id'), ['user_id'], unique=False)

    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('occupation_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('score BETWEEN 1 AND 5', name='ck_vote_score'),
    sa.ForeignKeyConstraint(['occupation_id'], ['occupations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'user_id', 'occupation_id', name='uq_vote')
    )
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_votes_occupation_id'), ['occupation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_votes_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_votes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_votes_user_id'))
        batch_op.drop_index(batch_op.f('ix_votes_room_id'))
        batch_op.drop_index(batch_op.f('ix_votes_occupation_id'))

    op.drop_table('votes')
    with op.batch_alter_table('room_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_room_members_room_id'))

    op.drop_table('room_members')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_recommendation_id'))

    op.drop_table('feedback')
    with op.batch_alter_table('criteria_weights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_criteria_weights_user_id'))
        batch_op.drop_index(batch_op.f('ix_criteria_weights_room_id'))

    op.drop_table('criteria_weights')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_student_id'))
        batch_op.drop_index(batch_op.f('ix_rooms_code'))

    op.drop_table('rooms')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_student_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_occupation_id'))

    op.drop_table('recommendations')
    with op.batch_alter_table('centres', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_centres_state'))
        batch_op.drop_index(batch_op.f('ix_centres_district'))
        batch_op.drop_index(batch_op.f('ix_centres_course_id'))

    op.drop_table('centres')
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_student_id'))

    op.drop_table('assessments')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_user_id'))
        batch_op.drop_index(batch_op.f('ix_students_state'))
        batch_op.drop_index(batch_op.f('ix_students_district'))

    op.drop_table('students')
    with op.batch_alter_table('market', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_state'))
        batch_op.drop_index(batch_op.f('ix_market_occupation_id'))

    op.drop_table('market')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_occupation_id'))
        batch_op.drop_index(batch_op.f('ix_courses_nsqf_level'))

    op.drop_table('courses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('occupations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_occupations_onet_code'))
        batch_op.drop_index(batch_op.f('ix_occupations_nsqf_level'))
        batch_op.drop_index(batch_op.f('ix_occupations_nco_code'))
        batch_op.drop_index(batch_op.f('ix_occupations_name_en'))

    op.drop_table('occupations')
    # ### end Alembic commands ###
