"""Add mentor_request

Revision ID: cdbe195361f9
Revises: d14e0fa75f33
Create Date: 2026-10-08 13:01:59.313033
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cdbe195361f9'
down_revision: Union[str, None] = 'd14e0fa75f33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentor_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mentor_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mentor_requests_user_id'), ['user_id'], unique=False)

    op.create_table('call_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_requests_requested_by_user_id'), ['requested_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_requests_room_id'), ['room_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_requests_room_id'))
        batch_op.drop_index(batch_op.f('ix_call_requests_requested_by_user_id'))

    op.drop_table('call_requests')
    with op.batch_alter_table('mentor_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mentor_requests_user_id'))

    op.drop_table('mentor_requests')
    # ### end Alembic commands ###
